### ISSUE TITLE
Your talk, the ghost example

### ISSUE THREAD

**Issue by stefangweichinger** [pschiffe/ansible-docker#2]
At first, thanks for your talk (on youtube), I learned some nice tricks by watching it and looking at your code.

Unfortunately your ghost example fails for me and I assume it might be related to ansible updates or so.
The task "[wait for mariadb to become ready]" fails for me:

```
TASK [wait for mariadb to become ready] *********************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: u\"hostvars['my-ghost-db']\" is undefined\n\nThe error appears to have been in ' [..] /ansible-docker/examples/ghost/ghost.yml': line 60, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: wait for mariadb to become ready\n      ^ here\n"}
```

I already tried to understand and fix your construct of determining the IP of the mariadb container, but so far without success ;-) maybe you could take a look ...

**Comment by pschiffe** [comment]
Hello, thanks for letting me know of your trouble. I've just updated all examples in this repository.

However, you problem is probably related to the fact, that you weren't running the `ansible` command from the `examples` directory, where the `ansible.cfg` file is stored, so the ansible didn't load the configuration for dynamic docker inventory, and thus the failed task couldn't find the `my-ghost-db` host. I've also added section to the [README](https://github.com/pschiffe/ansible-docker#examples) about this.

Let me know if you still have some troubles.

**Comment by stefangweichinger** [comment]
correct, works now for me as well, thanks. I will see how things go when I write my own configs based on your tricks ... I don't only use it on localhost but with $DOCKER_HOST=tcp://...  so that might give me some new issues (but not necessarily related to your code here).

**Comment by pschiffe** [comment]
Glad the examples work for you now and good luck with the remote docker host!
